config/routes.rb
Anglerfish::Application.routes.draw do
  devise_for :users
  get "port/index"
  get "pref/index"
  get "region/index"
  get "tides/index"
  resources :fishing_logs

  root 'tides#index'

  get '*path', controller: 'application', action: 'render_404'

end

app/models/fishing_log.rb
class FishingLog < ActiveRecord::Base
  belongs_to :user

  mount_uploader :fish_image, FishImageUploader

  validates :fish_name, :fishing_date, :fishing_time, presence: true
  validates :fish_image, file_size: { maximum: 0.5.megabytes.to_i }
  validates_numericality_of :fish_length, :fish_weight, greater_than: 0
end

app/controllers/fishing_logs_controller.rb
class FishingLogsController < ApplicationController
  before_action :set_fishing_log, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @search = current_user.fishing_logs.search(params[:q])
    @search.sorts = ['fishing_date desc'] if @search.sorts.empty?
    @fishing_logs = @search.result.page(params[:page])
  end

  def show
  end

  def new
    if params[:fishing_log]
      @fishing_log = FishingLog.new(fishing_log_params)
    else
      @fishing_log = FishingLog.new
    end
  end

  def edit
  end

  def create
    @fishing_log = current_user.fishing_logs.build(fishing_log_params)

    respond_to do |format|
      if @fishing_log.save
        format.html { redirect_to @fishing_log, notice: I18n.t('fishing_logs.create.notice') }
        format.json { render action: 'show', status: :created, location: @fishing_log }
      else
        format.html { render action: 'new' }
        format.json { render json: @fishing_log.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @fishing_log.user = current_user

      if @fishing_log.update(fishing_log_params)
        format.html { redirect_to @fishing_log, notice: I18n.t('fishing_logs.update.notice') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fishing_log.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fishing_log.destroy
    respond_to do |format|
      format.html { redirect_to fishing_logs_url, notice: I18n.t('fishing_logs.destroy.notice') }
      format.json { head :no_content }
    end
  end

private
  def set_fishing_log
    @fishing_log = current_user.fishing_logs.find(params[:id])
  end

  def fishing_log_params
    params.require(:fishing_log).permit(:fish_name, :fish_length, :fish_weight, :fishing_point_name, :fishing_method, :fishing_date, :fishing_time, :bait, :fish_image, :comment)
  end
end

app/helpers/fishing_logs_helper.rb
module FishingLogsHelper
end

app/views/fishing_logs/_form.html.haml
= simple_form_for @fishing_log, html: { class: 'form-horizontal', multipart: true } do |f|
  - if notification = f.error_notification
    = notification

  = f.input :fish_name
  = f.input :fish_length
  = f.input :fish_weight
  = f.input :fishing_point_name
  = f.input :fishing_method
  = f.input :fishing_date, as: :datepicker, readonly: true
  = f.input :fishing_time, as: :time
  = f.input :bait
  = f.input :fish_image, as: :file
  = f.input :comment, as: :text

  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/fishing_logs/edit.html.haml
- @page_title = t('helpers.titles.edit', model: t('activerecord.models.fishing_log'))
- @page_category = 'fishing_logs'

= render 'form'

app/views/fishing_logs/index.html.haml
- @page_title = t('helpers.titles.list', model: t('activerecord.models.fishing_log'))
- @page_category = 'fishing_logs'

%h4.search_title{ id: 'search_title' }
  %i.glyphicon.glyphicon-search
  = t('.search_title')
  %small
    - if params[:search].nil?
      %i.toggle-button.glyphicon.glyphicon-chevron-right
    - else
      %i.toggle-button.glyphicon.glyphicon-chevron-down
%div{ id: 'search_form_wrapper', style: (params[:search].nil? ? 'display: none;' : 'display: block;') }
  = search_form_for @search, url: fishing_logs_path, builder: SimpleForm::FormBuilder, html: { class: 'form-horizontal well form-search', id: 'fishing_logs_search_form' } do |f|
    = f.input :fish_name_cont, label: FishingLog.human_attribute_name(:fish_name)
    = f.input :fishing_point_name_cont, label: FishingLog.human_attribute_name(:fishing_point_name)

    .form-actions
      = f.button :submit, t('.search_form.button'), class: 'btn-info'

%p
  %span.pull-left= t('views.page_info.page', current: @fishing_logs.current_page, total: @fishing_logs.num_pages)
  %span.pull-right= t('views.page_info.records', offset: @fishing_logs.offset_value+1, limit: (@fishing_logs.offset_value+@fishing_logs.length), total: @fishing_logs.total_count)
  %span.clearfix
%table.table.table-striped.table-hover
  %tr
    %th= sort_link @search, FishingLog.human_attribute_name(:fish_name)
    %th= sort_link @search, FishingLog.human_attribute_name(:fish_length)
    %th= sort_link @search, FishingLog.human_attribute_name(:fish_weight)
    %th= sort_link @search, FishingLog.human_attribute_name(:fishing_point_name)
    %th= sort_link @search, FishingLog.human_attribute_name(:fishing_method)
    %th= sort_link @search, FishingLog.human_attribute_name(:fishing_date)
    %th= sort_link @search, FishingLog.human_attribute_name(:fishing_time)
    %th= sort_link @search, FishingLog.human_attribute_name(:bait)
    %th
    %th
    %th

  - @fishing_logs.each do |fishing_log|
    %tr
      %td= fishing_log.fish_name
      %td= number_to_human fishing_log.fish_length, units: { unit: 'cm', thousand: 'm' }
      %td= number_to_human fishing_log.fish_weight, units: { unit: 'g', thousand: 'kg' }
      %td= fishing_log.fishing_point_name
      %td= fishing_log.fishing_method
      %td= l fishing_log.fishing_date, format: :long
      %td= l fishing_log.fishing_time, format: :time_only
      %td= fishing_log.bait
      %td= link_to t('helpers.actions.show'), fishing_log, class: 'btn btn-default btn-xs'
      %td
        = link_to edit_fishing_log_path(fishing_log), class: 'btn btn-default btn-xs' do
          %i.glyphicon.glyphicon-edit
          = t('helpers.actions.edit')
      %td
        = link_to fishing_log, :method => :delete, :data => { :confirm => t('helpers.confirm.delete') }, class: 'btn btn-danger btn-xs btn-white' do
          %i.glyphicon.glyphicon-trash
          = t('helpers.actions.destroy')

= paginate @fishing_logs

%br

= link_to new_fishing_log_path, class: 'btn btn-primary btn-white' do
  %i.glyphicon.glyphicon-plus
  = t('.new_fishing_log')

app/views/fishing_logs/new.html.haml
- @page_title = t('helpers.titles.new', model: t('activerecord.models.fishing_log'))
- @page_category = 'fishing_logs'

= render 'form'

app/views/fishing_logs/show.html.haml
- @page_title = t('helpers.titles.show', model: t('activerecord.models.fishing_log'))
- @page_category = 'fishing_logs'

%div.show.fishing_log_show
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fish_name')}
    %div.col-sm-10
      = @fishing_log.fish_name
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fish_length')}
    %div.col-sm-10
      = number_to_human @fishing_log.fish_length, units: { unit: 'cm', thousand: 'm' }
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fish_weight')}
    %div.col-sm-10
      = number_to_human @fishing_log.fish_weight, units: { unit: 'cm', thousand: 'm' }
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fishing_point_name')}
    %div.col-sm-10
      = @fishing_log.fishing_point_name
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fishing_method')}
    %div.col-sm-10
      = @fishing_log.fishing_method
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fishing_date')}
    %div.col-sm-10
      = l @fishing_log.fishing_date, format: :long
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fishing_time')}
    %div.col-sm-10
      = l @fishing_log.fishing_time, format: :time_only
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.bait')}
    %div.col-sm-10
      = @fishing_log.bait
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.fish_image')}
    %div.col-sm-10
      - if @fishing_log.fish_image?
        %div.fish_image{ style: "background-image: url('#{@fishing_log.fish_image_url }')" }
  %div.row
    %div.col-sm-2
      %b #{t('activerecord.attributes.fishing_log.comment')}
    %div.col-sm-10
      %p
        = linebreak_to_br @fishing_log.comment

= link_to edit_fishing_log_path(@fishing_log), class: 'btn btn-primary btn-white' do
  %i.glyphicon.glyphicon-edit
  = t('helpers.actions.edit')