config/routes.rb
Anglerfish::Application.routes.draw do
  devise_for :users
  get "port/index"
  get "pref/index"
  get "region/index"
  get "tides/index"
  resources :fishing_logs

  root 'tides#index'

  get '*path', controller: 'application', action: 'render_404'

end

app/models/tide.rb
class Tide < ActiveResource::Base
  # 日付パラメータ（今日データを取得するための値）
  TIDE_GET_DATE_PARAM_VALUE_OF_TODAY = 'today'.freeze
  # 日付パラメータの日付フォーマット
  TIDE_GET_DATE_PARAM_FORMAT = '%Y/%m/%d'.freeze
  # 潮汐データの潮位レベルの単位
  TIDE_GET_RESULT_TIDE_LEVEL_UNIT = 'cm'.freeze

  attr_accessor :tides, :date, :sun_rise, :sun_set, :moon_rise, :moon_set

  alias_attribute :moon_age, :getsurei
  alias_attribute :tide_name, :shiomei
    
  self.site = 'http://www.e-tsuri.info/'
  self.format = :xml
  self.timeout = 20

  def self.today(port)
    self.get TIDE_GET_DATE_PARAM_VALUE_OF_TODAY, port
  end

  def self.get(date, port)
    port_param = port.presence || default_port_name
    date_param = convert_date_param(date)

    model = Tide.find(:one, from: '/tide', params: { p: port_param, d: date_param }) 
    model.tap {|m| bind_addtional_attr m } unless model.nil?
  end

  def high_tides
    if tides.at(0)[:tide_level] > tides.at(1)[:tide_level]
      [tides.at(0), tides.at(2)]
    else
      [tides.at(1), tides.at(3)]
    end
  end

  def low_tides
    if tides.at(0)[:tide_level] < tides.at(1)[:tide_level]
      [tides.at(0), tides.at(2)]
    else
      [tides.at(1), tides.at(3)]
    end
  end

private

  def self.bind_addtional_attr(model)
    model.date = Date.new(model.year.to_i, model.month.to_i, model.day.to_i)
    model.sun_rise= safe_parse_time(model.hinode)
    model.sun_set = safe_parse_time(model.hinoiri)
    model.moon_rise = safe_parse_time(model.tsukinode)
    model.moon_set = safe_parse_time(model.tsukinoiri)

    model.tides = model.tide.rstrip.split(/\r?\n/).map {|tide| 
      tide_infos = tide.chomp.split()

      time = safe_parse_time(tide_infos[0])
      tide_level = tide_infos[1].delete(TIDE_GET_RESULT_TIDE_LEVEL_UNIT).to_i
      { time: time, tide_level: tide_level }
    }
  end

  def self.default_port_name
    Port.first.name
  end

  def self.convert_date_param(date)
    return TIDE_GET_DATE_PARAM_VALUE_OF_TODAY unless date.present?

    begin
      Date.parse(date).strftime(TIDE_GET_DATE_PARAM_FORMAT)
    rescue
      TIDE_GET_DATE_PARAM_VALUE_OF_TODAY
    end
  end

  def self.safe_parse_time(time)
    return nil unless time.present?

    begin
      Time.parse(time)
    rescue
      nil
    end
  end
end

app/controllers/tides_controller.rb
class TidesController < ApplicationController
  def index
    @date = params[:date]
    @port_name = params[:port_name] || cookies[:last_search_port_name] || Port.first.name
    cookies.permanent[:last_search_port_name] = @port_name if @port_name.presence

    begin
      @tide = Tide.get(@date, @port_name)
      @weather = Weather.get(@port_name)
    rescue ActiveResource::ConnectionError, ActiveResource::ServerError
      # 接続先でエラーが発生しても無視する。
    end
  end
end

app/helpers/tides_helper.rb
module TidesHelper

  #
  # 月齢画像を表示する。
  #
  def moon_age_image(moon_age_str)
    moon_age = moon_age_str.to_f
    if moon_age >= 29 || moon_age < 2
      image = 'Moon-New.svg'
    elsif moon_age >= 2 && moon_age < 6
      image = 'Moon-Waxing-Crescent.svg'
    elsif moon_age >= 6 && moon_age < 10
      image = 'Moon-First-Quarter.svg'
    elsif moon_age >= 10 && moon_age < 14
      image = 'Moon-Waxing-Gibbous.svg'
    elsif moon_age >= 14 && moon_age < 17
      image = 'Moon-Full.svg'
    elsif moon_age >= 17 && moon_age < 21
      image = 'Moon-Waning-Gibbous.svg'
    elsif moon_age >= 21 && moon_age < 25
      image = 'Moon-Last-Quarter.svg'
    elsif moon_age >= 25 && moon_age < 29
      image = 'Moon-Waning-Crescent.svg'
    end
    "/assets/weather-icons/svg/#{image}"
  end

  #
  # 天気画像を表示する。
  #
  def weather_image(weather_icon_url)
    if weather_icon_url == 'http://weather.livedoor.com/img/icon/1.gif'
      image = 'Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/2.gif'
      image = 'Cloud-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/3.gif'
      image = 'Cloud-Rain-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/4.gif'
      image = 'Cloud-Snow-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/5.gif'
      image = 'Cloud-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/6.gif'
      image = 'Cloud-Rain-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/7.gif'
      image = 'Cloud-Snow-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/8.gif'
      image = 'Cloud.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/9.gif'
      image = 'Cloud-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/10.gif'
      image = 'Cloud-Rain-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/11.gif'
      image = 'Cloud-Snow-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/12.gif'
      image = 'loud-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/13.gif'
      image = 'Cloud-Rain-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/14.gif'
      image = 'Cloud-Snow-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/15.gif'
      image = 'Cloud-Rain.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/16.gif'
      image = 'Cloud-Rain-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/17.gif'
      image = 'Cloud-Rain-Alt.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/18.gif'
      image = 'Cloud-Snow.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/19.gif'
      image = 'Cloud-Rain-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/20.gif'
      image = 'Cloud-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/21.gif'
      image = 'Cloud-Snow.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/22.gif'
      image = 'Cloud-Rain.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/23.gif'
      image = 'Cloud-Snow.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/24.gif'
      image = 'Cloud-Snow-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/25.gif'
      image = 'Cloud-Snow.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/26.gif'
      image = 'Cloud-Snow.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/27.gif'
      image = 'Cloud-Snow-Sun.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/28.gif'
      image = 'Cloud-Snow.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/29.gif'
      image = 'Cloud-Snow.svg'
    elsif weather_icon_url == 'http://weather.livedoor.com/img/icon/30.gif'
      image = 'Cloud-Snow.svg'
    end

    "/assets/weather-icons/svg/#{image}"
  end
end

app/views/tides/index.html.haml
- @page_category = 'home'

.row
  .col-md-8
    .btn-group
      = button_tag class: 'btn btn-info', id: 'tide-date-select-button' do
        %i.glyphicon.glyphicon-calendar
        %span= l parse_date(@date), format: :long
      %input#tide-date-select-target.hide
        %input#tide-date-select-target-alt.hide{ value: parse_date(@date) }
      = link_to region_index_path, remote: true, class: 'btn btn-info', id: 'port-select-button', data: { type: :html } do
        %i.glyphiconcon.glyphicon-globe
        %span= @port_name
  .col-md-4
    = link_to new_fishing_log_path, method: :get, class: 'btn btn-primary btn-white', id: 'new-fishing-log-link' do
      %i.glyphiconcon.glyphicon-plus
        = t('.button.new_fishing_logs')
-if @tide
  .row
    .col-md-4.tide-info
      = image_tag '/assets/tide-icons/svg/tide.svg', class: 'tide-img'
      %p.tide-name= @tide.tide_name
    .col-md-4.tide-relation-info
      .moon-age
        %span
          = image_tag moon_age_image(@tide.moon_age)
        %span= @tide.moon_age
      .sun-rise
        %span
          = image_tag '/assets/weather-icons/svg/Sunrise.svg'
        %span= l @tide.sun_rise, format: :time_only
      .sun-set
        %span
          = image_tag '/assets/weather-icons/svg/Sunset.svg'
        %span= l @tide.sun_set, format: :time_only
    .col-md-4.weather-info
      - if @weather.present?
        - forecast_of_tide_day = @weather.forecast_of_date(@tide.date)
        - if forecast_of_tide_day.nil?
          .no-information.well
            %p= t('.weather_info.no_information_message')
        - else
          .forecast
            %span
              = image_tag weather_image(forecast_of_tide_day.image.url)
            %span= forecast_of_tide_day.telop
          .temprature
            %span
              = image_tag '/assets/weather-icons/svg/Thermometer.svg'
            %span.max= forecast_of_tide_day.temperature.max.nil? ? '-' : forecast_of_tide_day.temperature.max.celsius
            %span &nbsp;/&nbsp;
            %span.min= forecast_of_tide_day.temperature.min.nil? ? '-' : forecast_of_tide_day.temperature.min.celsius
            %span.unit
              = image_tag '/assets/weather-icons/svg/Degrees-Celcius.svg'
          .other-link
            = link_to t('.weather_info.other_link'), @weather.link, target: '_blank'
  %h3= t('.tide_table.high_tide_caption')
  %table.table
    %tr
      -@tide.high_tides.size.times do
        %th= t('.tide_table.date')
        %th= t('.tide_table.level')
    %tr
      -@tide.high_tides.each do |tide|
        %td= l tide[:time], format: :time_only unless tide.nil?
        %td= number_to_human tide[:tide_level], units: { unit: 'cm' }  unless tide.nil?

  %h3= t('.tide_table.low_tide_caption')
  %table.table
    %tr
      -@tide.low_tides.size.times do
        %th= t('.tide_table.date')
        %th= t('.tide_table.level')
    %tr
      -@tide.low_tides.each do |tide|
        %td= l tide[:time], format: :time_only unless tide.nil?
        %td= number_to_human tide[:tide_level], units: { unit: 'cm' }  unless tide.nil?

%div#port-select-dialog{ title: t('.dialog.port_select.title') }

= form_tag root_path, method: :get, class: 'hide', id: 'tide-search-form' do
  = date_field_tag :date, parse_date(@date), class: :date
  = text_field_tag :port_name, @port_name, class: :port_name
= form_tag new_fishing_log_path, method: :get, class: 'hide', id: 'new-fishing-log-form' do
  = date_field :fishing_log, :fishing_date, class: :date
  = text_field :fishing_log, :fishing_point_name, class: :port_name